import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]


[window]
opacity = 0.8
blur = true
padding = { x = 1, y = 1 }
decorations = 'None'


[keyboard]
bindings = [
{key = "B", mods = "Command | Shift", action = "ReceiveChar"}, 
]

